#!/bin/sh

# Prepare for running the Puppet-in-a-box. Obeys the environment variables
# documented below.

# CLUSTER_DOMAIN
# The DNS domain that serves to construct a number of default values for
# host names and URLs.
: ${CLUSTER_DOMAIN:-example.com}

# FOREMAN_ENC_HOST
#
# The URL to reach out to for Foreman integration: used to obtain
# so-called "node classification" data at the beginning of each Puppet run,
# and in return send back facts and reports.
: ${FOREMAN_ENC_HOST:-foreman.${CLUSTER_DOMAIN}}

configure_foreman_enc() {
    # https://theforeman.org/manuals/1.11/index.html#3.5.5FactsandtheENC
    cat > /etc/puppet/foreman.yaml <<EOF
:url: "https://${FOREMAN_ENC_HOST}"
:ssl_ca: "/var/lib/puppet/ssl/certs/ca.pem"
:ssl_cert: "/var/lib/puppet/ssl/certs/puppet.example.com.pem"
:ssl_key: "/var/lib/puppet/ssl/private_keys/puppet.example.com.pem"

# Advanced settings
:puppetdir: "/var/lib/puppet"
:puppetuser: "puppet"
:facts: true
:timeout: 10
:threads: null

EOF
}

register_proxy_in_foreman() {
    puppet apply -e \
           'class {"::foreman_proxy"}: 
                puppet   => true,
                puppetca => true,
                tftp     => false,
                dhcp     => false,
                dns      => false,
                bmc      => false,
                realm    => false
           }'
}


set -e -x
configure_foreman_enc
register_proxy_in_foreman

exec /usr/sbin/supervisord -n -c /etc/supervisor/supervisord.conf

