# Default foreman column view plugin configuration for an EPFL-STI cluster
# For more information see https://github.com/GregSutcliffe/foreman_column_view 
:column_view:
  :switch_address:
    :title: Switch Address
    :after: name
    :content: facts_hash['switch_address']
  :architecture:
    :title: Arch
    :after: model
    :content: facts_hash['architecture']
  :memorytotal:
    :title: Mem
    :after: architecture
    :content: facts_hash['memorysize']
  :comment:
    :title: Comment
    :after: hostgroup
    :content: comment
  :install_v:
    :title: install.sh version
    :after: last_report
    :content: facts_hash['install_sh_version']
