# Default foreman column view plugin configuration for an EPFL-STI cluster
# For more information see https://github.com/GregSutcliffe/foreman_column_view 
:column_view:
  :architecture:
    :title: Arch
    :after: last_report
    :content: facts_hash['architecture']
  :memorytotal:
    :title: Mem
    :after: architecture
    :content: facts_hash['memorysize']
  :comment:
    :title: Comment
    :after: last_report
    :content: comment
