#!/bin/bash
#
# Run foreman-installer to start things, then stay up forever

set -e -x

trap /bin/bash EXIT

if [ ! -f /etc/foreman/foreman-installer-answers.yaml ]; then
    cp /cluster.foreman/foreman-installer-answers.yaml /etc/foreman/
    foreman-installer
else
    /etc/init.d/apache2 start
    /etc/init.d/foreman start
    /etc/init.d/puppet start
fi

wait

