#!/bin/sh
#
# Install discovery-ready PXE templates as per
# http://theforeman.org/plugins/foreman_discovery/2.0/#3.1.1DefaultPXEtemplate
control() {
    hammer template dump --id 2 | grep 'configure_discovery_templates' && exit 0
}

set -e -x
control
tempfile="$(mktemp configure_discovery_templates.XXXXX)"
trap 'rm "$tempfile"' EXIT HUP TERM
hammer template dump --id 2 > "$tempfile" | perl -pe 's/^ONTIMEOUT .*$/ONTIMEOUT discovery/g'
echo >>"$tempfile" <<EOF

<%# Added by configure_discovery_templates %>

LABEL discovery
MENU LABEL Foreman Discovery
MENU DEFAULT
KERNEL boot/fdi-image/vmlinuz0
APPEND initrd=boot/fdi-image/initrd0.img rootflags=loop root=live:/fdi.iso rootfstype=auto ro rd.live.image acpi=force rd.luks=0 rd.md=0 rd.dm=0 rd.lvm=0 rd.bootif=0 rd.neednet=0 nomodeset proxy.url=https://FOREMAN_INSTANCE proxy.type=foreman
IPAPPEND 2

EOF
control

echo >&2 "Cannot update template"
exit 1

