#!/bin/sh
#
# Install discovery-ready PXE templates as per
# http://theforeman.org/plugins/foreman_discovery/2.0/#3.1.1DefaultPXEtemplate

export HOME=/root


getTemplateId() {
    templateId=0;
    if test -z "$1" || test "$#" -ne 1; then
        echo "Error: getTemplateId() needs the template name as input."
        exit 0
    else
        # echo "searching for $1's id";
        templateId=$(hammer template list --search "$1" | grep "$1" | grep -wo "^[0-9]*");
        if test $templateId -ne 0; then
            #returned value
            echo "$templateId"
        else
            echo "Error: no template's ID found for $1"
            exit 0
        fi
    fi
}

control() {
    if hammer template dump --id $1 | \
        grep 'configure_discovery_templates'; then
        exit 0
    fi
}

TID=$(getTemplateId "PXELinux global default");
control $TID; set -e -x
tempfile="$(mktemp /tmp/configure_discovery_templates.XXXXX)"
trap 'rm "$tempfile"' EXIT HUP TERM
hammer template dump --id $TID > "$tempfile" | perl -pe 's/^ONTIMEOUT .*$/ONTIMEOUT discovery/g'

cat >>"$tempfile" <<EOF

<%# Added by configure_discovery_templates %>

LABEL discovery
MENU LABEL Foreman Discovery
MENU DEFAULT
KERNEL boot/fdi-image/vmlinuz0
APPEND initrd=boot/fdi-image/initrd0.img rootflags=loop root=live:/fdi.iso rootfstype=auto ro rd.live.image acpi=force rd.luks=0 rd.md=0 rd.dm=0 rd.lvm=0 rd.bootif=0 rd.neednet=0 nomodeset proxy.url=<%= foreman_url %>  proxy.type=foreman  foreman.url=<%= foreman_url %> 
IPAPPEND 2

EOF
hammer template update --id $TID --file "$tempfile"
control $TID

echo >&2 "Cannot update template"
exit 1

