#!/bin/sh
# Install latest version of Hammer

export HOME=/root

control() {
    if hammer --version 2>&1 | \
        grep -q 'hammer_cli_foreman.*0\.1\.4' ; then
        exit 0
    fi
}    


control; set -e -x
gem install hammer_cli
gem install hammer_cli_foreman
control

echo >&2 "Cannot update hammer"
exit 1
